language: python
python: 3.6
install:
  - pip install -r requirements.txt
  - cp fonts/* venv/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/

script:
  - python3 -m flake8
  - python3 -m pytest test/*

